source 'https://rubygems.org'

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'airtable', group: :jekyll_plugins
gem 'bigdecimal'
gem 'activesupport'
gem 'json'
gem 'jekyll-watch'
gem 'html-proofer'
gem 'commonmarker'
